### ISSUE TITLE
[2] >>> Lỗi phân tích JSON Stack Trace: 	[SyntaxError] >>> Unexpected token < in JSON at position 1 tại JSON.parse ()

### ISSUE THREAD

**Issue by ooAkira** [belivipro9x99/thi-trac-nghiem#1]
Khi xoá toàn bộ dữ liệu trên hệ thống thi trắc nghiệm thì bị lỗi như vậy

**Comment by belivipro9x99** [comment]
I will take a look ASAP, please provide as much information as you can.

**Comment by belivipro9x99** [comment]
Okay so the problem is this feature is not intended to exist, my bad!
I will push a new release with this feature in just a few minutes. Please wait.

**Comment by belivipro9x99** [comment]
Đã fix tại commit ba79381ac5d8d6272b4f802ab135abee87ac1e92 và e5f8ae29eb8fa2a8c2881653bfe7e27436000d50
