### ISSUE TITLE
How to migrate data from old version?

### ISSUE THREAD

**Issue by nitrasnguyen** [belivipro9x99/thi-trac-nghiem#3]
For example, in the old version, you stored user accounts in an XML file. But in the current version, you stored them in JSON files. How can I manage to migrate the data easily?

**Comment by belivipro9x99** [comment]
Sorry but there is currently no tool available to convert old xml account database to json in current version yet.
You might want to do it manually or if you have a large dataset, write a little script that convert the xml file to json.
