### ISSUE TITLE
Admin Control Panel error

### ISSUE THREAD

**Issue by nitrasnguyen** [belivipro9x99/thi-trac-nghiem#5]
[3] >>> HTTP 500: (POST /api/config)
Stack Trace:
[-1 500] >>> Error Occurred: Undefined index: result tại /api/config.php:58
[8] >>> Undefined index: result

When clicking "Lưu thay đổi" in Admin Control Panel

**Comment by belivipro9x99** [comment]
Thank you for reporting!
I have confirmed that this issue is currently happening in the latest version. I will take a look and push a fix ASAP (maybe tomorrow).

**Comment by belivipro9x99** [comment]
I have resolved this issue in commit 2a091d15ed3c73f2dd3943869c1d11096443476a. A new release has been pushed, you can download it now.
