### ISSUE TITLE
500 INTERNAL SERVER ERROR in v1.0.2

### ISSUE THREAD

**Issue by nitrasnguyen** [belivipro9x99/thi-trac-nghiem#6]
the server did an oopsie
Lỗi [-1]: Error Occurred: filesize(): stat failed for /data/problems/thumbnail.default tại /api/problems/thumbnail.php dòng 16

The default thumbnail is not showing because this 500 INTERNAL SERVER ERROR

**Comment by belivipro9x99** [comment]
Hi! I've reuploaded the release binary, please redownload and check again if this resolves your problem.
